import { jsPDF } from 'jspdf';

export const generateArticlePDF = (article: any) => {
  const doc = new jsPDF();
  const margin = 20;
  const pageWidth = doc.internal.pageSize.getWidth();
  const contentWidth = pageWidth - (margin * 2);
  
  // Title
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  const titleLines = doc.splitTextToSize(article.title, contentWidth);
  doc.text(titleLines, margin, 30);
  
  let currentY = 30 + (titleLines.length * 10);
  
  // Metadata
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100);
  const date = article.created_at?.toDate ? article.created_at.toDate().toLocaleDateString() : new Date(article.created_at).toLocaleDateString();
  doc.text(`Category: ${article.category} | Contributor: ${article.suggested_by?.split('@')[0]} | Date: ${date}`, margin, currentY);
  
  currentY += 15;
  
  // Horizontal Line
  doc.setDrawColor(200);
  doc.line(margin, currentY, pageWidth - margin, currentY);
  
  currentY += 15;
  
  // Content
  doc.setFontSize(12);
  doc.setTextColor(0);
  
  // Simplified markdown stripping for PDF
  const cleanContent = article.content
    .replace(/#+\s/g, '') // Remove headers
    .replace(/\*\*/g, '') // Remove bold
    .replace(/\*/g, '')  // Remove italic
    .replace(/\[(.*?)\]\(.*?\)/g, '$1'); // Remove links
    
  const contentLines = doc.splitTextToSize(cleanContent, contentWidth);
  
  // Handle multi-page
  contentLines.forEach((line: string) => {
    if (currentY > 270) {
      doc.addPage();
      currentY = 20;
    }
    doc.text(line, margin, currentY);
    currentY += 7;
  });
  
  // Footer
  const totalPages = doc.internal.pages.length - 1;
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(`Generated by MindGrid Archive - Page ${i} of ${totalPages}`, pageWidth / 2, 285, { align: 'center' });
  }
  
  doc.save(`${article.title.replace(/\s+/g, '_').toLowerCase()}_mindgrid.pdf`);
};
